routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('article', 'ArticleController');

Route::get('search','ArticleController@search')->name('article.search');

Route::resource('api', 'RestfulController');

Route::post('/upload', 'FileUploadController@upload')->name('upload.add');
Route::post('/updatepassword', 'Auth\ResetPasswordController@update')->name('updatepassword');


Route::get('/home', 'HomeController@index')->name('home');

Route::get('send', 'MailController@send')->name('send');

Auth::routes();

Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    @yield('cssStyle')
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li><a class="nav-link" href="{{route('article.index')}}">Article</a></li>
                        {{-- <li><a class="nav-link" href="javascript:void(0)" id="fake">Search</a></li> --}}
                        @guest
                        @else
                        <li><a class="nav-link" href="{{route('home')}}">Home</a></li>
                        @endguest
                    </ul>

                    <div style="width:750px"> 
                        <!-- Search form -->
                        <form class="form-inline ">
                            <input class="form-control form-control-sm mr-3 w-235" type="text" placeholder="Search"
                                aria-label="Search" style="width:700px" id="search" name="search">
                            <i class="fas fa-search" aria-hidden="true"></i>
                        </form>
                    </div>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ ucfirst(Auth::user()->name) }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                    style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @include('sweetalert::alert')
    @yield('js')
    <script>
        $("#search").click(function () {
            Swal.fire({
                title: 'Sorry... Developing...',
                animation: false,
                customClass: {
                    popup: 'animated wobble'
                }
            })
        });
        // $(document).on("keyup","#search",function () {
        //     var id = $(this).val();
        //     $.ajax({
        //         url: "{{ route('article.search') }}",
        //         method:'GET',
        //         data:{id:id},
        //         dataType:'json',
        //         success:function(data){
        //             $('h4').html(data[0].content.replace(/\r\n/g,'<br>'));
        //         }
        //     })
        // });
    </script>
    
</body>

</html>

resources/views/layouts/form.blade.php
@include('layouts.message')

<section class="container">
    {!! Form::open(['action'=>$controllerMethod,'method'=>$httpMethod])!!}

    <div class="form-group">
        {{Form::label('title','Title')}}
        {{Form::text('title',$titleData,['class'=>'form-control','placeholder'=>'Title','required'=>'true',$disabled])}}
    </div>

    <div class="form-group">
        {{Form::label('content','Content')}}
        {{Form::textarea('content',$contentData,['class'=>'form-control','placeholder'=>'Body Text','minlength'=>'10','required'=>'true'])}}
    </div>

    <div class="form-group">
        <div class="col-md-6 col-md-offset-4">
            @php
            $secret = '6LfNH6EUAAAAAEtMHv8Xi5FvmRBq-o-t7B5WbdB8';
            $sitekey = '6LfNH6EUAAAAAG28W2x9Tjs_T_arstC6_hWkhXHC';
            $captcha = new \Anhskohbo\NoCaptcha\NoCaptcha($secret, $sitekey);
            echo $captcha->display();
            @endphp
        </div>
    </div>

    {{Form::submit('Submit',['class'=>'btn btn-primary'])}}
    {{Form::close()}}

    <br>

    @if (count($errors)>0)
    @foreach ($errors->all() as $error)
    <div class="alert alert-danger alert-dismissible in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{$error}}
    </div>
    @endforeach
    @endif
</section>

{{-- <form action="{{ url('article')}} " method="post">
<input type="hidden" name="_token" value="{{csrf_token()}}" required>
Title: <input type="text" name="title" class="form-control" maxlength="255" required>
<br>
Content: <textarea name="content" cols="30" rows="10" minlength="10" class="form-control" required></textarea>
<br>
<input type="submit" value="Submit" class="btn btn-primary">
</form> --}}

@section('js')
{!! NoCaptcha::renderJs() !!}
@stop

resources/views/layouts/message.blade.php
@if (session()->has('message'))
<div class="alert {{session()->get('type')}} alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>{{session()->get('alertType')}}</strong> {{session()->get('message')}}
</div>
@endif